{\rtf1\ansi\ansicpg1252\cocoartf2578
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\csgray\c0;}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs22 \cf2 \CocoaLigature0 --- \
- \
  hosts: WebServer\
  become: true\
  tasks:\
          - name: "1. Stop service"\
            tags: stop_apache\
            service:\
                name: apache2\
                state: stopped\
          - name: "2. Uninstall HTTPD/Apache"\
            tags: uninstall_apache\
            yum:\
                name: apache2\
                autoremove: yes\
                purge: yes\
                state: absent}